export const containerStyles = {
    minHeight: "calc(100vh - 80px)",
    width: "100vw",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    bgcolor: "#015077",
  },
  contentStyles = {
    margin: "20px 0",
    padding: "10px",
    width: "1088px",
    maxWidth: "95vw",
    background: "#fff",
    minHeight: "527px",
    // "@media screen and (max-width: 865px)": {
    //   display: "flex",
    //   flexDirection: "column",
    //   alignItems: "center",
    // },
  },
  itemsContainerStyles = {
    padding: "15px",
    height: "130px",
    bgcolor: "#F1F9FD",
    display: "flex",
    flexDirection: "column",
    direction: "rtl",
    cursor: "pointer",
    // "@media screen and (max-width: 1100px)": {
    //   flexDirection: "column",
    //   alignItems: "center",
    // },
  },
  buttonStyles = {
    width: "260px",
    height: "60px",
    fontSize: "20px",
    color: "#fff",
    bgcolor: "#005078",
    borderRadius: "23px",
    ":hover": {
      bgcolor: "#005078",
    },
  };
