export const containerStyles = {
    position: "fixed",
    top: 0,
    left: 0,
    height: "100vh",
    width: "100vw",
    bgcolor: "rgba(179, 179, 179, .5)",
    zIndex: "10",
  },
  modalContainerStyles = {
    position: "relative",
    padding: "5px",
    minHeight: "50vh",
    maxHeight: "80vh",
    width: "80vw",
    minwidth: "320px",
    bgcolor: "#096caa",
    borderRadius: "5px",
  },
  closeIconStyles = {
    position: "absolute",
    top: 0,
    right: 0,
    cursor: "pointer",
  };
